#theme: jekyll-theme-minimal
remote_theme: benbalter/retlab
title: Welcome to Sara Assecondi's webpage
author :
  name : Sara Assecondi
  email : sara.assecondi@gmail.com
  github : sassecon
  twitter : sassecon
  feedburner : nil
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
